// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGpGtNQsQ0QwGJtywnkdRxjfSihLcK9UY',
    appId: '1:323712181914:web:f7e2810cfe466168272123',
    messagingSenderId: '323712181914',
    projectId: 'biodata-2a4c8',
    authDomain: 'biodata-2a4c8.firebaseapp.com',
    storageBucket: 'biodata-2a4c8.firebasestorage.app',
    measurementId: 'G-TBCZPGVG98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN2giDtaFkM4DU9w6KLC67L5e7_ayt_AU',
    appId: '1:323712181914:android:d8711c3dd6c736f8272123',
    messagingSenderId: '323712181914',
    projectId: 'biodata-2a4c8',
    storageBucket: 'biodata-2a4c8.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGpGtNQsQ0QwGJtywnkdRxjfSihLcK9UY',
    appId: '1:323712181914:web:208b26057ce54306272123',
    messagingSenderId: '323712181914',
    projectId: 'biodata-2a4c8',
    authDomain: 'biodata-2a4c8.firebaseapp.com',
    storageBucket: 'biodata-2a4c8.firebasestorage.app',
    measurementId: 'G-SVZFDGZ8ZM',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASoSGvaiQWF8bIB7sCGgc5S4UsfQks-I4',
    appId: '1:323712181914:ios:d396040250705195272123',
    messagingSenderId: '323712181914',
    projectId: 'biodata-2a4c8',
    storageBucket: 'biodata-2a4c8.firebasestorage.app',
    iosBundleId: 'com.kambatha.seafarerbiodata',
  );

}